version: 2.1

executors:
  default_executor:
    working_directory: ~/talis-cdk-constructs
    docker:
      - image: cimg/node:14.17.3
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

orbs:
  node: circleci/node@4.5.1

jobs:
  build:
    executor: default_executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0b:38:6d:19:b1:30:d5:54:a9:07:29:e1:14:cc:ca:11"
      - checkout
      - node/install-packages
      - run:
          name: Define environment variable with lastest commit's message
          command: |
            echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Lint commit message
          command: echo "$COMMIT_MESSAGE" | npx commitlint
      - run:
          name: Lint code before building, to lint only source files
          command: npm run lint
      - run:
          name: Build code
          command: npm run build
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Semantic Release
          command: npx semantic-release

workflows:
  build:
    jobs:
      - build
