version: 2.1

executors:
  default_executor:
    working_directory: ~/talis-cdk-constructs
    docker:
      - image: cimg/node:14.17.3
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

orbs:
  node: circleci/node@4.5.1

jobs:
  build:
    executor: default_executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ee:b4:00:e6:23:5b:55:bb:fd:07:bc:73:9e:f7:89:9c" # shared.aspire@talis.com 'talis-cdk-constructs Deploy Key'
      - checkout
      - node/install-packages
      - run:
          name: Define environment variable with lastest commit's message
          command: |
            echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Lint commit message
          command: echo "$COMMIT_MESSAGE" | npx commitlint
      - run:
          name: Lint code before building, to lint only source files
          command: npm run lint
      - run:
          name: Build code
          command: npm run build
      - run:
          name: Build lambda worker example code
          command: cd examples/simple-lambda-worker && npm install && npm run build
      - run:
          name: Build authenticated api example code
          command: cd examples/simple-authenticated-api && npm install && npm run build
      - run:
          name: Run infra tests
          command: npm run infra-test
      - run:
          name: Deploy Authenticated Api for Integration Tests
          command: ./deploy/build/authenticated-api/deploy.sh
      - run:
          name: Semantic Release
          command: npx semantic-release

workflows:
  build:
    jobs:
      - build
