version: 2.1
commands:
  echo_build_number:
    description: "Echo the build number"
    steps:
      - run:
          name: 'Echo the build number'
          command: 'echo ${CIRCLE_BUILD_NUM}'

executors:
  default_executor:
    working_directory: ~/talis-cdk-constructs
    docker:
      - image: cimg/node:14.17.3
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

orbs:
  node: circleci/node@4.5.1

jobs:
  echo_build_number:
    machine: true
    steps:
      - echo_build_number
  build:
    executor: default_executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ee:b4:00:e6:23:5b:55:bb:fd:07:bc:73:9e:f7:89:9c" # shared.aspire@talis.com 'talis-cdk-constructs Deploy Key'
      - checkout
      - node/install-packages
      - run:
          name: Define environment variable with lastest commit's message
          command: |
            echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Build code
          command: npm run build
      - run:
          name: Lint code to lint only source files
          command: npm run lint
      - run:
          name: Run tests
          command: npm test
  master-build:
    executor: default_executor
    steps:
      - run:
          name: Lint commit message
          command: echo "$COMMIT_MESSAGE" | npx commitlint
      - run:
          name: Semantic Release
          command: npx semantic-release

workflows:
  build:
    jobs:
      - echo_build_number
      - be_kind_to_your_colleagues:
          type: approval
          filters:
            branches:
              ignore:
                - master
      - build:
          requires:
            - echo_build_number
      - master-build:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
